### ISSUE TITLE
Parse BIND SAMPLER

### ISSUE THREAD

**Issue by dj2** [google/amber#417]
The sampler bind call in amber script is not implemented yet.

**Comment by asuonpaa** [comment]
Do we want to support all the [sampler features of Vulkan](https://www.khronos.org/registry/vulkan/specs/1.1-extensions/man/html/VkSamplerCreateInfo.html)? That's a lot of data to be parsed in Amber. Do we already have a plan for the syntax?

**Comment by dj2** [comment]
We may want to support them in the future, but for now start with the absolute minimum and default all the other values with something that makes sense. We can add them as needed.

**Comment by asuonpaa** [comment]
Only supporting min/max filters, mipmap mode and UV address modes makes the syntax quite complex:

`SAMPLER sampler MAGFILTER filter MINFILTER filter MIPMAPMODE filter ADDRESSMODE_U modeu ADDRESSMODE_V modev`

I suppose it's still manageable, especially since we can use default values when some of those are missing.

**Comment by asuonpaa** [comment]
Looks like having an arbitrary number of parameters for sampler isn't trivial. You need to know what the last parameter is. Otherwise NextToken would consume the next command which we cannot undo. Would it make sense to do sampler as block like we do with shaders and pipeline? At least it would be more scalable that way. My previous example would become:

```
SAMPLER sampler
    MAGFILTER filter
    MINFILTER filter
    MIPMAPMODE filter
    ADDRESSMODE_U modeu
    ADDRESSMODE_V modev
END
```

**Comment by dj2** [comment]
With the single line version you can loop inside the parser until the token is EOL or EOS, the above could then be written as:

```
SAMPLER sampler \
    MAGFILTER filter \
    MINFILTER filter \
    MIPMAPMODE filter \
   ADDRESSMODE_U modeu \
   ADDRESSMODE_V modev
```

Although I'm not sure which is better, heh. Are there parameters we always have to pass to SAMPLER, like a binding or anything?

**Comment by asuonpaa** [comment]
Binding would be specified inside pipeline block the same way we do for textures. Sampler could be useful with all parameters being default.

I'll experiment with this single line version and let you know if it doesn't feel right.
