### ISSUE TITLE
Possible problem in the way Amber initializes a matrix uniform buffer

### ISSUE THREAD

**Issue by afd** [google/amber#616]
[The attached AmberScript file](https://github.com/google/amber/files/3474532/tmp_shader_test.amber.txt) (rename .amber.txt to .amber) captures a simple shader that declares a mat2x2 uniform m, populates it with 1.0 in every entry, and then writes:

```
vec4(m[1][0], 0.0, 0.0, 1.0)
```

to the output color.

This should give a red image.

On both SwiftShader and Intel Mesa (Vulkan) I get a black image.

The SPIR-V code that glslang has produced and that spirv-opt has optimized looks correct.

So I wonder, whether there might be an issue either in the way Amber is initializing this buffer, or perhaps in the way I've expressed the desired initialization in AmberScript:

```
BUFFER m DATA_TYPE mat2x2<float> DATA
 1.0 1.0 1.0 1.0
END
```

**Comment by dj2** [comment]
It should give a blue image as the framebuffer is BGRA, but regardless, blue is also not black, heh. So, if you dump the image out to a ppm file, it's all black in there? If you dump the buffer 0:0 out to a file does it have the expected `1 1 1 1` or something else in it?

I'm guessing the problem is the values in the buffer are wrong. Looking at the spirv, the `MatrixStride` is 16 and I'll bet we don't skip over those two extra floats when writing in the second column of 1's. So, the buffer _should_ have something like `1 1 0 0 1 1 0 0` in it.

**Comment by dj2** [comment]
Interesting, running the file here I get a red buffer as the output. This is running under MoltenVK 1.1.101.0.

**Comment by afd** [comment]
I think you're right that with the stride being 16 it is necessary to add padding to the buffer (I'm surprised that you get red with MoltenVk in that case - are you able to try out SwiftShader too?).

For the mat2x2 example I found that either changing the stride in the SPIR-V to 8, or setting the initialization to 1 1 0 0 1 1 0 0 worked.

However, I tried out the same thing for a similar shader with a mat2x3.  It does:

_GLF_color = vec4(m[1][2], 0.0, 0.0, 1.0);

and again should lead to red being rendered.

I find (as expected now) the same issue as before when I don't mess with the stride nor the initial values - a black image (see [bad.amber.txt](https://github.com/google/amber/files/3476082/bad.amber.txt)).

I get the red image as expected when I manually change the matrix stride to 12 (see [good_fix_stride.amber.txt](https://github.com/google/amber/files/3476081/good_fix_stride.amber.txt)) - a stride of 12 should work for a column major 2x3 matrix, I think.

But what I really want to do is keep the stride and add padding elements to the buffer.  I have tried this in [good_fix_initialization.amber.txt](https://github.com/google/amber/files/3476130/good_fix_initialization.amber.txt), but this leads to:

```
double free or corruption (out)
```

Here is part of the stack trace.  Any ideas?  Even if it turns out I'm misusing buffer initialization, it would be good to avoid a double-free and instead give an error.

```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff70388ad in __GI_abort () at abort.c:79
#2  0x00007ffff708fca8 in __libc_message (action=action@entry=do_abort, 
    fmt=fmt@entry=0x7ffff7199f6d "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff709640a in malloc_printerr (
    str=str@entry=0x7ffff719bcd8 "double free or corruption (out)")
    at malloc.c:5341
#4  0x00007ffff7097f20 in _int_free (av=0x7ffff73d0c40 <main_arena>, 
    p=0x13849d0, have_lock=<optimized out>) at malloc.c:4306
#5  0x0000000000a11d50 in __gnu_cxx::new_allocator<amber::Format::Component>::deallocate (this=0x13848b0, __p=0x13849e0)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/ext/new_allocator.h:125
#6  0x0000000000a11d20 in std::allocator_traits<std::allocator<amber::Format::Component> >::deallocate (__a=..., __p=0x13849e0, __n=2)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/alloc_traits.h:462
#7  0x0000000000a11cbb in std::_Vector_base<amber::Format::Component, std::allocator<amber::Format::Component> >::_M_deallocate (this=0x13848b0, 
    __p=0x13849e0, __n=2)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_vector.h:304
#8  0x0000000000a11c28 in std::_Vector_base<amber::Format::Component, std::alloc--Type <RET> for more, q to quit, c to continue without paging-- 
ator<amber::Format::Component> >::~_Vector_base (this=0x13848b0)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_vector.h:285
#9  0x0000000000a11b0a in std::vector<amber::Format::Component, std::allocator<amber::Format::Component> >::~vector (this=0x13848b0)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/stl_vector.h:570
#10 0x0000000000a115d9 in amber::Format::~Format (this=0x13848a0)
    at ../../src/format.cc:25
#11 0x0000000000a026ab in std::default_delete<amber::Format>::operator() (
    this=0x13849b0, __ptr=0x13848a0)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/unique_ptr.h:81
#12 0x00000000009f7d53 in std::unique_ptr<amber::Format, std::default_delete<amber::Format> >::~unique_ptr (this=0x13849b0)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/unique_ptr.h:274
#13 0x0000000000a0a9e3 in amber::Buffer::~Buffer (this=0x1384960)
    at ../../src/buffer.cc:62
#14 0x0000000000a045cb in std::default_delete<amber::Buffer>::operator() (
    this=0x1384888, __ptr=0x1384960)
    at /usr/bin/../lib/gcc/x86_64-linux-gnu/8/../../../../include/c++/8/bits/unique_ptr.h:81
```

**Comment by dj2** [comment]
The double free is definitely an issue that needs to be fixed. Adding values to the buffer in the amberscript file won't help. We need to fix this in the format class so that the system knows how many values to read, currently it probably thinks it needs 4 when, it needs to read 4 and make up 4.

I wonder if MoltenVK has a bug, or there is a bug in the spirv-cross conversion? The rules around std140 vs std430 layout are .... complicated.

I'll see if I can get SwiftShader compiling when I've got a chance.

@sarahM0 can you take a look and see if you can track down the double free from the good_fix_initialization.amber.txt file give above? (It's possibly also memory corruption when we fill in the buffer?)

For the other part, we're going to need to make the Format class smarter to figure out the elements needed for a mat2x2 in the various layouts.

**Comment by afd** [comment]
Any thoughts on how to proceed with this one?  I have a really nice [GraphicsFuzz shader](https://github.com/google/graphicsfuzz/issues/686) that is blocked by it.

**Comment by dj2** [comment]
Sorry, been digging myself out of a backlog hole, this go lost in the pile. Will take a look ....
