### ISSUE TITLE
Support dumping multiple framebuffers

### ISSUE THREAD

**Issue by asuonpaa** [google/amber#618]
Currently a command option -I is used for selecting which frame buffer gets dumped. Would be nice to be able to dump all framebuffers used in an amber file. Maybe just add an option that outputs framebuffername.png for each framebuffer used?

I could do a PR if people first agree how this should be implemented.

**Comment by dj2** [comment]
```
  -i <filename>             -- Write rendering to <filename> as a PNG image if it ends with '.png',
                               or as a PPM image otherwise.
  -I <buffername>           -- Name of framebuffer to dump. Defaults to 'framebuffer'.
  -b <filename>             -- Write contents of a UBO or SSBO to <filename>.
  -B [<desc set>:]<binding> -- Descriptor set and binding of buffer to write.
                               Default is [0:]0.
```

Looking at our current flags and how the buffer dumping works. I think we should change the framebuffer name variable into a `vector`. For buffers we append to a single file, but for framebuffers that won't work. So, I'd propose we write to a filename based off the `-i` flag where we do something like (if -i out_file.png is provided) `out_file-fb_name.png` where fb_name is the framebuffer name. This would only happen if multiple framebuffers are requested. If a single buffer is requested just `out_file.png` would be used.

We could then add a flag like `-A` for all framebuffers which creates the full list for you if that's needed.

**Comment by paulthomson** [comment]
Passing thought: what about some way of listing each buffer and its output file one-after-the-other, so that the behavior is very clear and explicit:

`buffer_1 output1.png buffer_2 output2.ppm buffer_3 output3.bin buffer_4 output4.bin`

With VkScript, I assume there will be (implicitly) `framebuffer` and maybe `0:0`, `0:1`, etc., but in AmberScript, all the buffers can be explicitly named. If the output files end with .png or .ppm, a conversion is done, but otherwise, the raw binary is dumped (although it might need to be error if the buffer format doesn't make sense for the output extension). This also somewhat unifies the dumping of framebuffers vs. buffers. Of course, this doesn't fit particularly well with the existing flags.

**Comment by dj2** [comment]
We could do some thing like pair up -i and -I flags?

`-i first.png -I framebuffer1 -i second.ppm -I otherbuffer -i third.png -I some_other_buffer`

then they just match, so framebuffer1 goes to first.png and so on? If you have one more -i then -I it defaults to `framebuffer`. If you have more then 1 extra it's an error?

For data buffers, we already have -b and -B which do the dumping, we may want to extend to have similar behaviour if we do this for images.

@dneto0 any thoughts on this API?

**Comment by dneto0** [comment]
+1 to being explicit about pairing up `-i` and `-I.

For vkrunner scripts, I'm concerned about the colon in the filename.  Does Windows handle a colon in the filename, or does it error out since it looks like a drive letter?  If Windows is ok with it, then I'm ok.

In general, I like having long option names, and add short options as shortcuts.  The long options act as natural documentation for those who read the help quickly.

Separately, do we need a way to introspect a script, e.g. "in this amber script, list the named buffers". Then an external script can process that to make sane command lines to extract the buffers. I'd call this option --query  :-)

**Comment by asuonpaa** [comment]
The current usage of `-B` doesn't support multiple compute pipelines. For example _pipeline1_ might have a _buffer1_ bound as 0:0, and _pipeline2_  a _buffer2_ bound to the same location. Is there a reason why SSBOs to dump couldn't be specified by the buffer name instead of the binding location? That way it wouldn't differ from how it works for frame buffers.

I suppose we could also check if the buffer name contains : and then use it like it's done right now, but then we should warn if the amber file contains multiple pipelines with the same binding.

Multiple frame buffer dump support was quite trivial to add. The support for multiple SSBOs sounds like more work, so maybe do that as a separate task?

**Comment by paulthomson** [comment]
That is a good point. I agree that it would be better to use buffer names instead of binding locations. @dj2 Do you agree?

Why do we differentiate between framebuffers and data buffers? Could we just use `-i` and `-I` for named data buffers as well? Although perhaps we would just use `-b` and `-B` in this case (assuming "i" stands for "image").

**Comment by dj2** [comment]
@asuonpaa good catch. So, historically, we started with VkScript which didn't have multiple pipelines and didn't have named buffers. We added the dumping capabilities at that time. With AmberScript, you're correct in that it isn't great.

So, yes, we should probably modify the `-B` to support _both_ named buffers or the descriptor `0:0` syntax. We have two things we could do if multiple pipelines have the same binding, we either error out and say to name the buffer to dump, or, we dump _both_ of them to the output file and prefix with the pipeline name, so you'd get something like:

```
pipeline1 0:0
  1 23 4

pipeline2 0:0
  4 5 8
```

or something along those lines.

Please file a bug for the framebuffer `-B` changes and a separate issue for the need to run compute pipeline first, as that sounds weird.

**Comment by dj2** [comment]
You can write multiple buffers to a single file, you can't do that with images. So, we separated them to make it clear what was happening.
